sudo: required
services:
  -docker

before_install:
  - docker build -t engr-mfahad/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true engr-mfahad/react-test npm test

after_success:
  - docker build -t engr-mfahad/multi-client ./client
  - docker build -t engr-mfahad/multi-nginx ./nginx
  - docker build -t engr-mfahad/multi-server ./server
  - docker build -t engr-mfahad/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID --password-stdin
  # Take those images and push them to docker hub
  - docker push engr-mfahad/multi-client
  - docker push engr-mfahad/multi-nginx
  - docker push engr-mfahad/multi-server
  - docker push engr-mfahad/multi-worker